import { Inter } from 'next/font/google';
import './globals.css';
import NavBar from '@/components/dashboard/NavBar';
import SideBar from '@/components/dashboard/SideBar';
import { Card } from '@/components/ui/card';
import { Toaster } from 'sonner';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div className="w-full h-screen flex flex-col">
                    <NavBar />

                    <div className={`flex flex-grow overflow-hidden`}>
                        <SideBar />

                        <div className="p-4 w-full h-full overflow-y-auto">
                            <Card>{children}</Card>
                        </div>
                    </div>
                </div>
                <Toaster />
            </body>
        </html>
    );
}
